CC = riscv32-unknown-elf-gcc
CFLAGS ?= -static -mcmodel=medany -march=rv32im -nostdlib
LINKER_SCRIPT ?= memory.ld

$(PROGRAM_NAME).elf: $(C_SOURCES) memory.ld
	$(CC) $(CFLAGS) -T $(LINKER_SCRIPT) $< -o $@

$(PROGRAM_NAME).dis: $(PROGRAM_NAME).elf
	riscv32-unknown-elf-objdump -D $< > $@

.PHONY: all clean

all: $(PROGRAM_NAME).elf $(PROGRAM_NAME).dis

clean:
		rm -rf $(PROGRAM_NAME).dis \
			     $(PROGRAM_NAME).elf
